---
title: "College tuition, diversity, and pay"
author: "Zahra Khoshmanesh, , "
date: "4/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#libraries
library(tidyverse)
```




```{r}

# Get the Data

tuition_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_cost.csv')

tuition_income <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_income.csv') 

salary_potential <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv')

historical_tuition <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/historical_tuition.csv')

diversity_school <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/diversity_school.csv')

# Or read in with tidytuesdayR package (https://github.com/thebioengineer/tidytuesdayR)
# PLEASE NOTE TO USE 2020 DATA YOU NEED TO USE tidytuesdayR version ? from GitHub

# Either ISO-8601 date or year/week works!

# Install via devtools::install_github("thebioengineer/tidytuesdayR")

#tuesdata <- tidytuesdayR::tt_load('2020-03-10')
#tuesdata <- tidytuesdayR::tt_load(2020, week = 11)


#tuition_cost <- tuesdata$tuition_cost


```

Let us look at the datasets we have:

1) Diversity Dataset

```{r}
diversity_school %>% glimpse()
```

Diversity vs. State

```{r}
diversity_school %>%
  group_by(state,category) %>% 
  mutate(enrollment_rate=round((enrollment/total_enrollment),2)*100) %>% 
  summarise(mean_enrollment_rate_per_state=mean(enrollment_rate)) %>% 
  arrange(desc(mean_enrollment_rate_per_state)) %>% 
    ggplot(aes(x=state,weight=mean_enrollment_rate_per_state,fill=category)) +
  geom_bar()+
  coord_flip()
  

```

Diversity & Tuition

```{r}
diversity_enroll_rate <- diversity_school %>%
  group_by(state,category) %>% 
  mutate(enrollment_rate=round((enrollment/total_enrollment),2)*100) %>% 
  summarise(mean_enrollment_rate_per_state=mean(enrollment_rate))


tuition_cost %>% 
  group_by(state) %>% 
  summarise(in_state_tuition=mean(in_state_tuition),
            out_of_state_tuition=mean(out_of_state_tuition)) %>% 
  merge(diversity_enroll_rate) %>% 
  ggplot(aes(x=in_state_tuition,y=mean_enrollment_rate_per_state, color=category)) +
  geom_line()





```


Is there any relation between ethnicity and enrollment rate and in state tuition

```{r}

tuition_cost %>% 
  group_by(state) %>% 
  summarise(in_state_tuition=mean(in_state_tuition),
            out_of_state_tuition=mean(out_of_state_tuition)) %>% 
   merge(diversity_enroll_rate) %>% 
   filter(category %in% c("Asian","White","Black","American Indian / Alaska Native")) %>%
  ggplot(aes(x=in_state_tuition,y=mean_enrollment_rate_per_state, color=category)) +
  geom_point()

```

Is there any relation between ethnicity and enrollment rate and out of state tuition

```{r}

tuition_cost %>% 
  group_by(state) %>% 
  summarise(in_state_tuition=mean(in_state_tuition),
            out_of_state_tuition=mean(out_of_state_tuition)) %>% 
   merge(diversity_enroll_rate) %>% 
   filter(category %in% c("Asian","White","Black","American Indian / Alaska Native")) %>%
  ggplot(aes(x=out_of_state_tuition,y=mean_enrollment_rate_per_state, color=category)) +
  geom_point()

```

